### ISSUE TITLE
tag {literal} doesn't work properly

### ISSUE THREAD

**Issue by FathoniRokhman** [imperez/vscode-smarty#1]
Hello @imperez , I'm currently working with smarty framework.
Tag {literal} that doesn't work, this is the capture

![capture](https://cloud.githubusercontent.com/assets/4667862/14553445/dbc99042-0310-11e6-88c0-e9eeccdfcc50.JPG)

**Comment by FathoniRokhman** [comment]
comparing with netbeans, look like this :
![capture](https://cloud.githubusercontent.com/assets/4667862/14553577/7caf2742-0311-11e6-906d-610bb6967c54.JPG)

**Comment by imperez** [comment]
Thanks for the issue! I'll see if I can find some time soon to look into this bug.

**Comment by imperez** [comment]
I opened a ticket #5775 with VSCode since right now documentation is pretty empty on how to fix this problem.

**Comment by imperez** [comment]
Sorry for taking so long on this. It took a bit of trial and error while finding extra time to work on this but I just pushed a new update that adds support for the literal tag. Give it a look and let me know if you have any issues.
