### ISSUE TITLE
How to change brackets setting

### ISSUE THREAD

**Issue by aggrosoft** [imperez/vscode-smarty#2]
Sorry if this is a newb question, but how do I configure the brackets setting. I tried adding the following to my user settings:

`    "smarty.brackets": ["[{", "}]"]`

and also

`    "smarty": {
      "brackets": ["[{", "}]"]
    }`

but nothing seems to work. I need the smarty tags to be like 

`[{ assign var="foo" value="bar" }]`

**Comment by imperez** [comment]
Hey thanks for the issue. I don't see any documentation to support that style of brackets in VSCode. I even checked some of the existing languages and came up empty. So right now it seems like a limitation of the editor.
