### ISSUE TITLE
Emmet/HTML snippets don't work

### ISSUE THREAD

**Issue by bugproof** [imperez/vscode-smarty#22]
It works fine in PHP files but it doesn't in smarty *.tpl

![image](https://user-images.githubusercontent.com/3116731/67553286-1aeebd80-f70d-11e9-9651-8bf4da02cfe8.png)

I even have these settings:
```
"emmet.syntaxProfiles": {
			"tpl": "html"
		},
		// "emmet.includeLanguages": {
		// 	"smarty": "html"
		// },
		"emmet.triggerExpansionOnTab": true,
```

what's the deal?

**Comment by bugproof** [comment]
ok it seems to work with `"emmet.includeLanguages"`. syntaxProfiles is not needed https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types

**Comment by digiage** [comment]
still can't make it work. not sure why

    "emmet.includeLanguages": {
        "tpl": "html"
    }
![image](https://user-images.githubusercontent.com/73428488/124288462-7b283a80-db51-11eb-9e6a-d2dbcde7eb1d.png)

**Comment by digiage** [comment]
ok. works with : 
```
      "emmet.includeLanguages": {
          "smarty": "html"
      }
```

**Comment by edpol27** [comment]
tab key doesn't expand abbreviation. It works in html, but not in smarty.
ml10 goes to <ml10></ml10>
with ctrl+space I see a correct suggestion
`"emmet.triggerExpansionOnTab": true` option is enabled

UPD:
`
"files.associations": {
"*.tpl": "smarty",
"*.master": "smarty"
}
`
this helped
