### ISSUE TITLE
Formatting the entire document does not work.

### ISSUE THREAD

**Issue by mreduar** [imperez/vscode-smarty#25]
When I try to format the whole document the indentation does not work properly. It only works when you select a particular block and format the selection.
![example](https://i.imgur.com/Wp3CgDh.gif "Example")

**Comment by sbreuerm3** [comment]
Wait... you're writing an issue for smarty template support plugin in the smarty vscode plugin repository?

**Comment by mreduar** [comment]
> Wait... you're writing an issue for smarty template support plugin in the smarty vscode plugin repository?

I don't remember what happened xD, it was 2 years ago.

**Comment by mreduar** [comment]
I guess there is no point in leaving the issue open, I don't think it will be solved, I don't use the add-on anymore.
